Global:
  FirstRun: true
sites:
  Car:
    cookie: ''
    enabled: true
    tasks:
    - daily_claim_task
    - daily_checkin
  Cyanbug:
    cookie: ''
    enabled: true
    tasks:
    - daily_shotbox
    - daily_checkin
  LemonHD:
    cookie: ''
    enabled: true
    tasks:
    - daily_checkin
    - daily_lottery
  Lgs:
    cookie: ''
    enabled: true
    tasks:
    - daily_shotbox
    - daily_checkin
  Qingwa:
    cookie: ''
    enabled: true
    tasks:
    - daily_shotbox
    - daily_checkin
  Vicomo:
    cookie: ''
    enabled: true
    tasks:
    - daily_shotbox
    - daily_checkin
    - daily_vs_boss
  Zm:
    cookie: ''
    enabled: true
    tasks:
    - daily_shotbox
    - daily_checkin
    - medal_bonus
